language: android

jdk:
  - oraclejdk8

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'


before_install:
  - yes | sdkmanager "platforms;android-28"

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
sudo: false

before_script:
  # Create and start an emulator for instrumentation tests.
  - chmod +x gradlew
  - chmod +x ./travis_build.sh
# script for build and release via Travis to Bintray
script: ./travis_build.sh

notifications:
  email: false

# cache between builds
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - "$HOME/gcloud-sdk/"